### ISSUE TITLE
Usage of "Null value" (in particular for the JSON serialization)

### ISSUE THREAD

**Issue by richsalz** [ietf-wg-httpapi/linkset#3]
Copied from https://github.com/dret/I-D/issues/146 ; here's the comments.

raised by @idg10 at https://mailarchive.ietf.org/arch/msg/httpapi/lvYDG1jI-x6-My2yllvkke1akeA:

I think I might have found an inconsistency in “Section 4.2.2. Link Context Object” of draft-wilde-linkset-07. This states that in cases where “no value is to be provided for the "anchor" member”, a link context object MUST provide an: "anchor" member with null value ("anchor": "").
The example in parentheses appears to contradict the text that it purports to illustrate: it shows an empty string, which is not the same thing as a null value in JSON. (This is inside “Section 4.2 JSON Document” so JSON types and values are relevant here. Moreover, since draft-wilde-linkset-07 doesn’t define what it means by null, the obvious interpretation of “null” in this context is the definition given by the JSON spec.)
If a null value is required (as the text states), then the example should be "anchor": null, shouldn’t it?
Alternatively, if the example is correct as it stands, then shouldn’t the preceding text say “an empty string value” instead of “null value”?
Also, “4.2.3. Link Target Object” does the same thing regarding href, offering ("href": "") as an example of what it calls a “null value”.
If the intention is that “null value” is just the language being used to describe an empty string intended to signify an absent value, it would be helpful to clarify that, since JSON defines null as a type and also as a distinct value.

added by @darrelmiller at https://mailarchive.ietf.org/arch/msg/httpapi/ZVbV4u_MEZPyyaedGEG-2Rdqejo:

In addition to Ian’s comment, it would be useful to understand why anchor is a required property. RFC8288 states,

    When present, the anchor parameter overrides this with another URI,

Why does the JSON serialization make this property required and then have to deal with issues around null vs empty string?
@richsalz

**Comment by hvdsomp** [comment]
I rephrase the issue hoping that doing so will yield a discussion that leads to a satisfactory solution.

There are really two issues here regarding the JSON serialization:
1. Should "anchor" be optional rather than mandatory?
2. How to handle unspecified values for "anchor" and "href" & language in the I-D associated with the choice

**Regarding (1):** 

An optional "anchor":
- creates consistency with the optional use of "anchor" in the HTTP Link header and the application/linkset serialization for Linksets
- creates tension with the desire - expressed in the I-D - to explicitly provide anchors in order to avoid problems with determining link context, understanding that Linksets are standalone resources and that - most likely - the URI of the Linkset that delivers a serialized set of links is not the intended context for those links
- might result in parsing problems, for example, in case someone would be so clever and resourceful to register an "anchor" link relation type

**Regarding (2):**

- The intention is to communicate that the value (for "anchor" or "href") was not set
- The question is how this is best achieved in JSON: by an empty string value ("") or a null value (null)? Hopefully JSON experts can provide guidance.

**Comment by dret** [comment]
hey @richsalz , @hvdsomp and i worked on addressing this issue. please check the commit https://github.com/ietf-wg-httpapi/linkset/commit/8e1892b450dda54a666388f43b03ac885209e949 and let us know. or just close this issue if you think we've addressed it successfully. thanks!

**Comment by richsalz** [comment]
you might want to bring the diff up to the mailing list.  but you guys are admins (as co-authors) so you can close when you think it's done.

**Comment by dret** [comment]
we removed any mention of NULL because that really was the wrong terminology. we're now speaking of empty strings which does resolve this issue.
