### ISSUE TITLE
Relative reference

### ISSUE THREAD

**Issue by philarcher** [ietf-wg-httpapi/linkset#42]
MNot:

* 4.2.2 Link Context Object -- 'SHOULD NOT be a relative reference' -- what are the consequences of violating this SHOULD NOT?

PhilA I think this restriction makes sense but we should probably say why:

Each link context object MAY have an "anchor" member with a value that represents the link context.  If present, this value MUST be a URI Reference and SHOULD NOT be a relative reference as per Section 4.1 of [RFC3986]. This is because the Linkset is itself a stand alone resource and may be used entirely separately from the context of the origin server.

**Comment by hvdsomp** [comment]
We don't think the motivation for not using relative references should be repeated in the sentence mentioned by @mnot (and in other similar sentences) because the motivation is given quite explicitly in 4.1 and the intro to 4.2. Both sections state:

In order to support use cases where "application/linkset" documents are re-used outside the context of an HTTP interaction, it is RECOMMENDED to make them self-contained by adhering to the following guidelines:

- For every link provided in the set of links, explicitly provide the link context using the "anchor" attribute.
- For link context ("anchor" attribute) and link target ("href" attribute), use URI References that are not relative references (as defined in Section 4.1 of [RFC3986]). 

@mnot, please let us know if not OK.

**Comment by mnot** [comment]
I think so - that gives good context.

**Comment by philarcher** [comment]
LGTM, thanks

**Comment by hvdsomp** [comment]
Closing because consensus reached.
